### PR TITLE
Added dutch translation 1.2.5.5

### PR DESCRIPTION
**Pull request by gmkey**

### CODE REVIEW

**Comment by christianTF** [comment]
Hi @gmkey
We are still in progress of adapting the Mailserver widget, therefore some additional changes (and possibly changes of changes) will coming soon.
I give you a message, when we have finished that changes (so you don’t need to push every little change).

Lg Christian

**Comment by gmkey** [comment]
Hi Christian,

that makes good sense. Just ping me when you plan to release a new version. Not sure if I can respond every time, but we’ll see.

best regards,
Gijs

**Comment by christianTF** [comment]
Hi Gijs,

I've added a list of changes and the compare link for a diff of all 1.2.5.5->1.4 changes here:
https://github.com/mschlenstedt/Loxberry/issues/666#issuecomment-448941760

We are still in Pre-Release, but try to get it to Release until Sunday. 

Are you registered in loxforum.com? I'm currently struggling to reach all translators on a single point.

Best regards,
Christian

**Comment by gmkey** [comment]
Hi Christian,

Thanks for the heads-up

Op 20 dec. 2018 om 11:14 heeft Christian Fenzl <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:

> 
> I've added a list of changes and the compare link for a diff of all 1.2.5.5->1.4 changes here:
> #666 (comment) <https://github.com/mschlenstedt/Loxberry/issues/666#issuecomment-448941760>
> We are still in Pre-Release, but try to get it to Release until Sunday.
> 
ah, trying to push everything before X-Mas? 

> Are you registered in loxforum.com <http://loxforum.com/>? I'm currently struggling to reach all translators on a single point.
> 
Now I am: gmkey
With a family of five I’m not sure if I can get my translation  done in time. 

Best Regards,

Gijk

**Comment by christianTF** [comment]
Hi Gijk,

if you cannot catch up until xmas, no problem - we will ship on Sunday because we need to fix kernel drivers for Pi 3A+ and 3B+ (bug in network stack), but would do another small release if we get translations later.

I add further details in the forum.

Best regards, 
Christian

**Pull request merged**
