### PR TITLE
sethosts: fix interface determination

### PR DESCRIPTION
**Pull request by gahujipo**

### CODE REVIEW

**Review by Woersty — CHANGES_REQUESTED** [review]
Is eth0 always the first interface? 
By the way a ' is missing.

**Comment by Woersty** [comment]
We used a completely different way - you list the devices.
We check the routing table.
Don't think it will work this way.

**Comment by gahujipo** [comment]
> By the way a ' is missing.

oh, sorry for that. 

> Is eth0 always the first interface?

You may be right, that eth0 or the first device in the list is not always the right interface. 

>We used a completely different way - you list the devices.
We check the routing table.
Don't think it will work this way.

You query the device and with that you query the IP. But querying the routing table does not work with this awk expression. 

I pushed a simplier expression with regex which should do the work.

**Comment by Woersty** [comment]
Just for info:
```
loxberry@loxberrydev:~ $ route -n | awk '/UG/ {print $8}'
wlan0
loxberry@loxberrydev:~ $ ls -1 /sys/class/net | head -1
eth0
```
😈

**Review by Woersty — COMMENTED** [review]
Better

**Review by Woersty — APPROVED** [review]

**Comment by gahujipo** [comment]
> Better

is the default route on raspberry named "default"? On my test VM it begins with the network mask instead of the string default. That's what confused me.

**Comment by Woersty** [comment]
Yes. It is.
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         FritzBox.woerst 0.0.0.0         UG    0      0        0 eth0
192.168.178.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**Pull request merged**
