### PR TITLE
add execute command to PHP SDK

### PR DESCRIPTION
**Pull request by nufke**
Pull request to execute (system) commands on the LoxBerry using the JSON-RPC interface implemented in PHP. Quite handy if you need some LoxBerry information in Node-RED

### CODE REVIEW

**Review by christianTF — COMMENTED** [review]
Heavy concerns about security

**Comment by nufke** [comment]
I understand the concern, but note that for remote connections authentication is anyhow required.

FYI, OpenWRT offers similar capabilities
https://documenter.getpostman.com/view/14290/SzKPUgEo#6834ee4d-6dd3-483a-875f-a1c8dbb4d358

**Comment by mschlenstedt** [comment]
Where is authentication for remote connections required? Some webspace in loxberry does noauthentication at all. This is maybe different to other systems.

**Comment by nufke** [comment]
See https://loxwiki.atlassian.net/wiki/spaces/LOXBERRY/pages/1236861368/LoxBerry+JsonRPC:

> Interface URL
> http://localhost:80/admin/system/jsonrpc.php
> For localhost, no authentication is required (But! For remote connections, the user credentials are required! So use localhost) 

When calling LoxBerry via JSON-RPC from another machine, using http://loxberryIPaddres:80/admin/system/jsonrpc.php it will require a username and password.

**Comment by nufke** [comment]
I noticed that executing a `whoami` via JSON-RPC via localhost (no authentication) returns `loxberry` as user. To address the security concerns, can we execute PHP commands under a different account (e.g. rpcuser)? In this way we can better manage and restrict the commands to be executed by such rpcuser.

**Comment by mschlenstedt** [comment]
Just for documentation: we had an internal discussion about the security concerns:

- Apache webserver runs as user loxberry, so no direct root commands are possible
- Authentication is indeed active for json-rpc (it is available in the admin-webspace)
- Authentication is disabled for all localhost connections. For such a connection an (password protected) access is needed

Conclusion: json-rpc is as secure as everything else on the loxberry (only password protection available). Users should never make LoxBerry available to public access - with or without json-rpc.

**Pull request merged**
